/**
 * Kanairoex LLM + Multimodal Bridge
 * Priority order for generation:
 *   1. External native backends (Ollama, LM Studio, llama.cpp server, custom)
 *   2. Browser WebLLM (WebGPU)
 *   3. Classic rule / memory / mini-transformer engine
 */
(function (root) {
  'use strict';

  const SYSTEM_PROMPT = `You are Kanairoex, a private offline-first AI assistant running entirely on the user's device.
You are helpful, truthful, and concise. You respect the user's local knowledge base and cognitive memory.
When you are unsure, say so. Prefer clear explanations suitable for students and professionals.
You do not claim to be a cloud service or to have real-time web access unless the user has explicitly used an online lookup.`;

  function buildContextSnippet() {
    const parts = [];
    try {
      if (root.CognitiveEngine && typeof root.CognitiveEngine.snapshot === 'function') {
        const snap = root.CognitiveEngine.snapshot();
        if (snap && snap.goal) parts.push('Current goal: ' + snap.goal);
        if (snap && snap.facts && snap.facts.length) {
          parts.push('Working facts:\n- ' + snap.facts.slice(-8).join('\n- '));
        }
      }
    } catch (_) {}
    try {
      if (root.Knowledge && typeof root.Knowledge.search === 'function') {
        // caller may pass richer context
      }
    } catch (_) {}
    return parts.join('\n\n').slice(0, 3500);
  }

  /** Try native external backend first (Ollama / LM Studio / …) */
  async function tryExternalLLM(userText, opts) {
    opts = opts || {};
    if (!root.ExternalLLM || !root.ExternalLLM.isActive()) return null;

    const context = opts.context || buildContextSnippet();
    const system = opts.system || SYSTEM_PROMPT;

    try {
      const result = await root.ExternalLLM.generate(userText, {
        system: system,
        context: context || undefined,
        temperature: opts.temperature != null ? opts.temperature : 0.7,
        max_tokens: opts.max_tokens || 1024,
        stream: !!opts.stream,
        onToken: opts.onToken,
        backend: opts.backend,
        model: opts.model
      });

      const st = root.ExternalLLM.status();
      return {
        source: 'external-llm',
        backend: result.backend || st.activeBackend,
        model: result.model,
        reply: result.content,
        thinking: 'Generated by ' + (result.backend || 'external') + ' (' + (result.model || '') + ')',
        streamed: !!result.streamed,
        usage: result.usage || null
      };
    } catch (err) {
      console.warn('[LLM Bridge] external generation failed', err);
      return {
        source: 'external-llm-error',
        reply: null,
        error: err.message || String(err)
      };
    }
  }

  /** Browser WebLLM (WebGPU) */
  async function tryWebLLM(userText, opts) {
    opts = opts || {};
    if (!root.LocalLLM) return null;
    const st = root.LocalLLM.status();
    if (!st.ready && !opts.autoLoad) return null;

    if (!st.ready && opts.autoLoad) {
      const r = await root.LocalLLM.init(opts.modelId);
      if (!r.ok) return null;
    }

    const context = opts.context || buildContextSnippet();
    const system = opts.system || SYSTEM_PROMPT;

    try {
      const result = await root.LocalLLM.generate(userText, {
        system: system,
        context: context || undefined,
        temperature: opts.temperature != null ? opts.temperature : 0.7,
        max_tokens: opts.max_tokens || 1024,
        stream: !!opts.stream,
        onToken: opts.onToken
      });

      return {
        source: 'webllm',
        model: result.model,
        reply: result.content,
        thinking: 'Generated by WebLLM (' + (result.model || 'unknown') + ')',
        streamed: !!result.streamed,
        usage: result.usage || null
      };
    } catch (err) {
      console.warn('[LLM Bridge] WebLLM generation failed', err);
      return {
        source: 'webllm-error',
        reply: null,
        error: err.message || String(err)
      };
    }
  }

  /**
   * Unified entry: External → WebLLM → null (classic fallback)
   */
  async function tryLocalLLM(userText, opts) {
    opts = opts || {};
    // 1. Native external backends (strongest / full hardware)
    const ext = await tryExternalLLM(userText, opts);
    if (ext && ext.reply) return ext;

    // 2. Browser WebLLM
    const web = await tryWebLLM(userText, opts);
    if (web && web.reply) return web;

    // Both failed or unavailable
    if (ext && ext.error) return ext;
    if (web && web.error) return web;
    return null;
  }

  async function tryMultimodal(image, userText, opts) {
    opts = opts || {};
    if (!root.Multimodal) return null;

    let st = root.Multimodal.status();
    if (!st.ready) {
      const r = await root.Multimodal.init({ caption: true, vqa: true });
      if (!r.ok) {
        return { source: 'multimodal-error', error: r.error, reply: null };
      }
    }

    try {
      const result = await root.Multimodal.understand(image, userText || '');
      const answer = result.answer || result.caption || '';
      return {
        source: 'multimodal',
        method: result.method,
        reply: answer,
        caption: result.caption,
        thinking: 'Multimodal understanding (' + (result.method || 'caption') + ')',
        meta: result.meta
      };
    } catch (err) {
      console.warn('[Multimodal Bridge] failed', err);
      return {
        source: 'multimodal-error',
        reply: null,
        error: err.message || String(err)
      };
    }
  }

  function isLLMCommand(text) {
    const t = String(text || '').trim().toLowerCase();
    return /^(load|init|start|enable|connect|use)\s+(local\s+)?(llm|model|phi|llama|gemma|ollama|lm\s*studio|lmstudio)|llm status|model status|backend status|unload (llm|model)|list models|switch model|probe (backends|ollama|lmstudio)|use (ollama|lmstudio|webllm|classic)/i.test(t);
  }

  async function handleLLMCommand(text) {
    const t = String(text || '').trim();
    const lower = t.toLowerCase();

    // ---- Status ----
    if (/llm status|model status|backend status/i.test(lower)) {
      const lines = ['**AI Backend Status**', ''];

      // External
      if (root.ExternalLLM) {
        const es = root.ExternalLLM.status();
        lines.push('### External (native)');
        lines.push('- Active backend: ' + (es.activeBackend || '—'));
        lines.push('- Active model: ' + (es.activeModel || '—'));
        const probes = await root.ExternalLLM.probeAll();
        ['ollama', 'lmstudio', 'llamacpp', 'custom'].forEach(function (id) {
          const p = probes[id] || {};
          const preset = root.ExternalLLM.getPreset(id);
          lines.push('- ' + (preset.icon || '') + ' **' + preset.name + '** (`' + preset.baseUrl + '`): ' +
            (p.online ? ('online — ' + (p.models || []).length + ' model(s)') : ('offline' + (p.error ? ' (' + p.error + ')' : ''))));
          if (p.online && p.models && p.models.length) {
            lines.push('  Models: ' + p.models.slice(0, 8).join(', ') + (p.models.length > 8 ? '…' : ''));
          }
        });
        lines.push('');
      }

      // WebLLM
      if (root.LocalLLM) {
        const s = root.LocalLLM.status();
        lines.push('### Browser WebLLM');
        lines.push('- Ready: ' + (s.ready ? 'yes' : 'no'));
        lines.push('- Model: ' + (s.modelId || '—'));
        lines.push('- WebGPU: ' + (s.hasWebGPU ? 'available' : 'not available'));
        lines.push('- Error: ' + (s.error || 'none'));
        lines.push('');
      }

      // Multimodal
      if (root.Multimodal) {
        const mm = root.Multimodal.status();
        lines.push('### Multimodal');
        lines.push('- Ready: ' + (mm.ready ? 'yes' : 'no') + ' (' + (mm.mode || '—') + ')');
      }

      return { source: 'llm-command', reply: lines.join('\n') };
    }

    // ---- List models ----
    if (/list models/i.test(lower)) {
      const lines = ['**Available models**', ''];
      if (root.ExternalLLM) {
        const probes = await root.ExternalLLM.probeAll();
        ['ollama', 'lmstudio', 'llamacpp', 'custom'].forEach(function (id) {
          const p = probes[id];
          const preset = root.ExternalLLM.getPreset(id);
          if (p && p.online && p.models && p.models.length) {
            lines.push('### ' + preset.icon + ' ' + preset.name);
            p.models.forEach(function (m) { lines.push('- `' + m + '`'); });
            lines.push('');
          }
        });
      }
      if (root.LocalLLM) {
        lines.push('### Browser WebLLM (recommended)');
        root.LocalLLM.listRecommended().forEach(function (m) {
          lines.push('- `' + m.id + '` — ' + m.name + ' (' + m.size + ')');
        });
      }
      lines.push('\nActivate with: `use ollama llama3.2` or `use lmstudio <model>` or `load llm Phi-3.5-mini-instruct-q4f16_1-MLC`');
      return { source: 'llm-command', reply: lines.join('\n') };
    }

    // ---- Probe ----
    if (/probe (backends|ollama|lmstudio|all)/i.test(lower)) {
      if (!root.ExternalLLM) return { source: 'llm-command', reply: 'ExternalLLM module missing.' };
      const probes = await root.ExternalLLM.probeAll();
      const lines = ['**Backend probe results**', ''];
      Object.keys(probes).forEach(function (id) {
        const p = probes[id];
        const preset = root.ExternalLLM.getPreset(id);
        lines.push(preset.icon + ' **' + preset.name + '** — ' + (p.online ? 'ONLINE' : 'offline'));
        if (p.models && p.models.length) lines.push('  ' + p.models.join(', '));
        if (p.error) lines.push('  ' + p.error);
      });
      return { source: 'llm-command', reply: lines.join('\n') };
    }

    // ---- Use / connect external ----
    // Patterns: "use ollama", "use ollama llama3.2", "connect lmstudio", "use lmstudio mistral"
    const useMatch = t.match(/^(?:use|connect|enable)\s+(ollama|lm\s*studio|lmstudio|llamacpp|llama\.cpp|custom|webllm|classic)\s*([^\s].*)?$/i);
    if (useMatch) {
      let backend = useMatch[1].toLowerCase().replace(/\s+/g, '').replace('llama.cpp', 'llamacpp');
      if (backend === 'lmstudio') backend = 'lmstudio';
      const modelArg = (useMatch[2] || '').trim();

      if (backend === 'classic') {
        if (root.ExternalLLM) root.ExternalLLM.setActive(null, null);
        if (root.LocalLLM) await root.LocalLLM.unload();
        return { source: 'llm-command', reply: 'Switched to **classic** engine (rules + memory + mini-transformer).' };
      }

      if (backend === 'webllm') {
        if (root.ExternalLLM) root.ExternalLLM.setActive(null, null);
        if (!root.LocalLLM) return { source: 'llm-command', reply: 'WebLLM module missing.' };
        const r = await root.LocalLLM.init(modelArg || undefined);
        return {
          source: 'llm-command',
          reply: r.ok
            ? ('WebLLM ready: **' + r.modelId + '**' + (r.cached ? ' (cached)' : ''))
            : ('WebLLM load failed: ' + (r.error || 'unknown'))
        };
      }

      // External backend
      if (!root.ExternalLLM) return { source: 'llm-command', reply: 'ExternalLLM module missing.' };
      const info = await root.ExternalLLM.probe(backend);
      if (!info.online) {
        return {
          source: 'llm-command',
          reply: '**' + root.ExternalLLM.getPreset(backend).name + '** is offline.\n\n' +
            (backend === 'ollama'
              ? 'Install from https://ollama.com then run `ollama serve` (or just open the Ollama app).'
              : backend === 'lmstudio'
                ? 'Open LM Studio → Developer / Server tab → Start server (default port 1234). Enable CORS if prompted.'
                : 'Start the server and ensure it exposes an OpenAI-compatible API.') +
            (info.error ? '\n\nDetail: ' + info.error : '')
        };
      }

      let model = modelArg;
      if (!model && info.models && info.models.length) model = info.models[0];
      if (!model) {
        return {
          source: 'llm-command',
          reply: backend + ' is online but no models found. ' +
            (backend === 'ollama' ? 'Run `ollama pull llama3.2` in a terminal.' : 'Load a model in the app first.')
        };
      }

      // Verify model exists (fuzzy)
      if (info.models && info.models.length && info.models.indexOf(model) === -1) {
        const fuzzy = info.models.find(function (m) { return m.indexOf(model) !== -1 || model.indexOf(m) !== -1; });
        if (fuzzy) model = fuzzy;
      }

      root.ExternalLLM.setActive(backend, model);
      return {
        source: 'llm-command',
        reply: 'Connected to **' + root.ExternalLLM.getPreset(backend).name + '** using model **' + model + '**.\n\nOpen-ended questions will now use this backend. Type `use classic` to switch back.'
      };
    }

    // ---- Unload ----
    if (/unload (llm|model)/i.test(lower)) {
      if (root.ExternalLLM) root.ExternalLLM.setActive(null, null);
      if (root.LocalLLM) await root.LocalLLM.unload();
      return { source: 'llm-command', reply: 'All local LLM backends deactivated. Classic engine is active.' };
    }

    // ---- Load WebLLM (legacy commands) ----
    const m = t.match(/(?:load|init|start|enable)\s+(?:local\s+)?(?:llm|model)\s+([^\s]+)/i) ||
              t.match(/load\s+llm\s+([^\s]+)/i);
    if (m || /^(load|init)\s+(local\s+)?llm\s*$/i.test(t)) {
      if (root.ExternalLLM) root.ExternalLLM.setActive(null, null); // prefer explicit WebLLM load
      if (!root.LocalLLM) return { source: 'llm-command', reply: 'LocalLLM (WebLLM) module is not present.' };
      const modelId = m ? m[1] : root.LocalLLM.DEFAULT_MODEL;
      const r = await root.LocalLLM.init(modelId);
      if (r.ok) {
        return {
          source: 'llm-command',
          reply: r.cached
            ? ('WebLLM already ready: **' + r.modelId + '**')
            : ('WebLLM loaded: **' + r.modelId + '**\n\nChat normally — answers will use the browser model when appropriate.')
        };
      }
      return {
        source: 'llm-command',
        reply: 'Failed to load WebLLM: ' + (r.error || 'unknown') +
          (r.needsWebGPU ? '\n\nThis browser does not expose WebGPU.' : '')
      };
    }

    return { source: 'llm-command', reply: 'Unknown LLM command. Try: `llm status`, `list models`, `use ollama`, `use lmstudio`, `load llm`, `probe backends`.' };
  }

  function shouldPreferLLM(userText) {
    // Prefer if either external or webllm is ready
    const hasExternal = root.ExternalLLM && root.ExternalLLM.isActive();
    const hasWeb = root.LocalLLM && root.LocalLLM.status().ready;
    if (!hasExternal && !hasWeb) return false;

    const t = String(userText || '').trim();
    if (t.length < 12) return false;
    if (/^(balance|wallet|pay|p2p|create token|remember that|teach|srs|tech status|help|guide|export|import|clear|use |load |unload |probe |list models|llm status|backend status)\b/i.test(t)) {
      return false;
    }
    return true;
  }

  root.LLMBridge = {
    tryLocalLLM,
    tryExternalLLM,
    tryWebLLM,
    tryMultimodal,
    isLLMCommand,
    handleLLMCommand,
    shouldPreferLLM,
    SYSTEM_PROMPT,
    buildContextSnippet
  };
})(typeof window !== 'undefined' ? window : globalThis);
